shared:
  ingress_domain: "tap.bullblock.net"
  ingress_issuer: "tap-ingress-selfsigned"

  image_registry:
    project_path: "dev.registry.tanzu.vmware.com/sliang-tap"
    secret:
      name: "registry-credentials"
      namespace: "tap-install"


  kubernetes_version: "1.27.3"


ceip_policy_disclosed: true

profile: full

supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "dev.registry.tanzu.vmware.com"
    repository: "sliang-tap/supply-chain"
  gitops:
    ssh_secret: ""

contour:
  envoy:
    service:
      type: LoadBalancer

buildservice:
  kp_default_repository: "dev.registry.tanzu.vmware.com/sliang-tap/build-service"
  kp_default_repository_secret:
    name: "registry-credentials"
    namespace: "tap-install"

tap_gui:
  metadataStoreAutoconfiguration: true
  app_config:
    auth:
      allowGuestAccess: true
    catalog:
      locations:
        - type: url
          target: https://raw.githubusercontent.com/bullblock/tap-f5demo/main/catalog-info.yaml

metadata_store:
  ns_for_export_app_cert: "tap-install"
  app_service_type: ClusterIP

policy:
  tuf_enabled: false
